version: "3.8"

services:
  app:
    build:
      context: app
    ports:
      - "5000"
    networks:
      - my_network
    environment:
      MYSQL_HOST: mysql
    volumes:
      - app_data:/app/data

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3309:3306'
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  app_data:
  mysql_data: