#-- dev compose

version: '3'

services:
  app:
    build: 
      context: app
    container_name: python-server
    command: python wsgi.py --host=0.0.0.0 --port=5000 --reload 
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/bd_plantas
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true

  mongodb:
    build:
      context: ./mongo 
    container_name: mongodb  
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:




