# services:
#   app:
#     build:
#       context: app
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mysql
#     environment:
#       MYSQL_HOST: mysql
#     volumes:
#       - app_data:/app/data

#   mysql:
#     build: ./mysql/
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db'
#       MYSQL_ROOT_PASSWORD: 'root'
#     ports:
#       - '3306:3306'
#     volumes:
#       - mysql_data:/var/lib/mysql

#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - app
#     ports:
#       - "80:80"

# volumes:
#   app_data:
#   mysql_data:

#-- dev compose

services:
  app:
    build: 
      context: app
    container_name: python-server
    command: flask run --host=0.0.0.0 --port=5000 --reload 
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
  

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


#------


#-- compose test--
# version: '3'

